name: HeapDump
main: me.bloodmc.heap.HeapPlugin
load: STARTUP
version: 0.2
api-version: 1.13
commands:
   heapdump:
      description: Creates a JVM heap dump for memory analysis.
      permission: me.bloodmc.heap
      usage: /heapdump
